version: '3.8'

services:
  app:
    build: .
    ports:
      - '7000:7000'
    environment:
      DATABASE: postgres://${PG_USER}:${PG_PASSWORD}@db:5432
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: